2020-11-26 10:40:00.004 | ERROR    | __main__:<module>:21 - An error has been caught in function '<module>', process 'MainProcess' (10284), thread 'MainThread' (12712):
Traceback (most recent call last):

> File "E:/pyAutoTest/pyTest/TestDemo.py", line 21, in <module>
    a = my_function(1,1,-2)
        ©¸ <function my_function at 0x0000020C50D050D0>

  File "E:/pyAutoTest/pyTest/TestDemo.py", line 17, in my_function
    a = 1/(x+y+z)
           ©¦ ©¦ ©¸ -2
           ©¦ ©¸ 1
           ©¸ 1

ZeroDivisionError: division by zero
2020-11-26 10:40:00.011 | INFO     | __main__:<module>:22 - None
2020-11-26 10:41:35.638 | INFO     | __main__:my_function:18 - 0.25
2020-11-26 10:41:35.638 | INFO     | __main__:<module>:22 - 0.25
2020-11-26 10:41:58.964 | ERROR    | __main__:<module>:21 - An error has been caught in function '<module>', process 'MainProcess' (9080), thread 'MainThread' (2276):
Traceback (most recent call last):

> File "E:/pyAutoTest/pyTest/TestDemo.py", line 21, in <module>
    a = my_function(1,1,-2)
        ©¸ <function my_function at 0x000001ED4F885048>

  File "E:/pyAutoTest/pyTest/TestDemo.py", line 17, in my_function
    a = 1/(x+y+z)
           ©¦ ©¦ ©¸ -2
           ©¦ ©¸ 1
           ©¸ 1

ZeroDivisionError: division by zero
2020-11-26 15:54:02.499 | ERROR    | __main__:<module>:21 - An error has been caught in function '<module>', process 'MainProcess' (14824), thread 'MainThread' (13808):
Traceback (most recent call last):

> File "E:/pyAutoTest/pyTest/TestDemo.py", line 21, in <module>
    a = my_function(1,1,-2)
        ©¸ <function my_function at 0x000002BDA5627048>

  File "E:/pyAutoTest/pyTest/TestDemo.py", line 17, in my_function
    a = 1/(x+y+z)
           ©¦ ©¦ ©¸ -2
           ©¦ ©¸ 1
           ©¸ 1

ZeroDivisionError: division by zero
2020-11-26 15:56:24.945 | ERROR    | __main__:<module>:21 - An error has been caught in function '<module>', process 'MainProcess' (4584), thread 'MainThread' (15260):
Traceback (most recent call last):

> File "E:/pyAutoTest/pyTest/TestDemo.py", line 21, in <module>
    a = my_function(1,1,-2)
        ©¸ <function my_function at 0x0000028D7CB77048>

  File "E:/pyAutoTest/pyTest/TestDemo.py", line 17, in my_function
    a = 1/(x+y+z)
           ©¦ ©¦ ©¸ -2
           ©¦ ©¸ 1
           ©¸ 1

ZeroDivisionError: division by zero
2020-11-26 15:56:25.663 | DEBUG    | TestDemo:<module>:10 - That's it ,beautiful and simple logging!
